version: "2"

services:
  nexus:
    image: sonatype/nexus3
    restart: unless-stopped
    container_name: nexus
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
  
volumes:
  nexus-data: {}
